lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 36000 # Tiempo de vida del token (10 horas)
    # token_ttl: 3600 # Tiempo de vida del token (1 hora)